<?xml version="1.0" encoding="utf-8"?><Database Name="webproject" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.0.28;Initial Catalog=webproject;Integrated Security=True" SettingsObjectName="сSharpProject.Properties.Settings" SettingsPropertyName="webprojectConnectionString" Provider="System.Data.SqlClient" />
</Database>